//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.19 at 03:14:26 AM BOT 
//
//@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.jcp.org/xml/ns/persistence/orm")

@XmlSchema(
        namespace = "http://java.sun.com/xml/ns/persistence/orm",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
            @XmlNs(prefix = "xs",
                    namespaceURI = "http://www.w3.org/2001/XMLSchema"),
             @XmlNs(prefix = "xsi",
                    namespaceURI = "http://www.w3.org/2001/XMLSchema-instance"),
            @XmlNs(prefix = "java",
                    namespaceURI = "http://jcp.org/en/jsr/detail?id=270"),
            @XmlNs(prefix = "jpa",
                    namespaceURI = "http://java.sun.com/xml/ns/persistence/orm")

        }
)
package com.github.yracnet.jpa.spec;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
